# Linear Regression with a Real Dataset

This notebook uses a real dataset to predict the prices of houses in California.   

## The Dataset
  
The [dataset for this exercise](https://developers.google.com/machine-learning/crash-course/california-housing-data-description) is based on 1990 census data from California. The dataset is old but still provides a great opportunity to learn about machine learning programming.

In [1]:
import pandas as pd
import tensorflow as tf
from matplotlib import pyplot as plt

# Adjust the granularity of reporting.
# pd.options.display.max_ros = 10
# pd.options.display.float_format = "{:.2f}".format

Import the .csv file into a pandas DataFrame and scales the values in the label (`median_house_value`):

Scaling `median_house_value` puts the value of each house in units of thousands. Scaling will keep loss values and learning rates in a friendlier range.  

Although scaling a label is usually *not* essential, scaling features in a multi-feature model usually *is* essential.

In [2]:
# Import the dataset.
training_df = pd.read_csv(filepath_or_buffer="https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv")

# Scale the label.
training_df["median_house_value"] /= 1000.0

# Print the first rows of the pandas DataFrame.
training_df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66.9
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80.1
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85.7
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73.4
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65.5

## Examine the dataset

A large part of most machine learning projects is getting to know your data. The pandas API provides a `describe` function that outputs the following statistics about every column in the DataFrame:

* `count`, which is the number of rows in that column. Ideally, `count` contains the same value for every column. 

* `mean` and `std`, which contain the mean and standard deviation of the values in each column. 

* `min` and `max`, which contain the lowest and highest values in each column.

* `25%`, `50%`, `75%`, which contain various [quantiles](https://developers.google.com/machine-learning/glossary/#quantile).

In [3]:
# Get statistics on the dataset.
training_df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207.300912
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115.983764
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14.999000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119.400000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180.400000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500.001000

In [5]:
from linear_regression import build_model, train_model_real_dataset

In [18]:
# Hyperparameters
learning_rate = 0.05
epochs = 18
batch_size = 3

# Specify feature and label:
# the model aims to predict the house value based on solely total_rooms
my_feature = "population"
my_label = "median_house_value"

my_model = None
my_model = build_model(learning_rate)
weight, bias, epochs, rmse = train_model_real_dataset(my_model,
                                         training_df,
                                         my_feature,
                                         my_label,
                                         epochs, batch_size)
print("\nThe learned weight for your model is %.4f" % weight)
print("The learned bias for your model is %.4f\n" % bias )

Epoch 1/18
5667/5667 [==============================] - 15s 2ms/step - loss: 30440.9883 - root_mean_squared_error: 174.4735
Epoch 2/18
5667/5667 [==============================] - 14s 2ms/step - loss: 20170.9395 - root_mean_squared_error: 142.0244
Epoch 3/18
5667/5667 [==============================] - 14s 2ms/step - loss: 18863.7266 - root_mean_squared_error: 137.3453
Epoch 4/18
5667/5667 [==============================] - 14s 2ms/step - loss: 18174.3359 - root_mean_squared_error: 134.8122
Epoch 5/18
5667/5667 [==============================] - 14s 2ms/step - loss: 18375.0859 - root_mean_squared_error: 135.5547
Epoch 6/18
5667/5667 [==============================] - 14s 2ms/step - loss: 18011.6504 - root_mean_squared_error: 134.2075
Epoch 7/18
5667/5667 [==============================] - 14s 2ms/step - loss: 17980.8965 - root_mean_squared_error: 134.0929
Epoch 8/18
5667/5667 [==============================] - 14s 2ms/step - loss: 18007.6855 - root_mean_squared_error: 134.1927
Epoch 9/18
5667/5667 [==============================] - 14s 2ms/step - loss: 17984.2812 - root_mean_squared_error: 134.1055
Epoch 10/18
5667/5667 [==============================] - 14s 2ms/step - loss: 18141.0977 - root_mean_squared_error: 134.6889
Epoch 11/18
5667/5667 [==============================] - 5567s 983ms/step - loss: 18121.0078 - root_mean_squared_error: 134.6143
Epoch 12/18
5667/5667 [==============================] - 13s 2ms/step - loss: 17999.2051 - root_mean_squared_error: 134.1611
Epoch 13/18
5667/5667 [==============================] - 15s 3ms/step - loss: 18259.9492 - root_mean_squared_error: 135.1294
Epoch 14/18
5667/5667 [==============================] - 13s 2ms/step - loss: 18318.0762 - root_mean_squared_error: 135.3443
Epoch 15/18
5667/5667 [==============================] - 10s 2ms/step - loss: 18298.9219 - root_mean_squared_error: 135.2735
Epoch 16/18
5667/5667 [==============================] - 14s 2ms/step - loss: 18139.5605 - root_mean_squared_error: 134.6832
Epoch 17/18
5667/5667 [==============================] - 14s 2ms/step - loss: 18048.4434 - root_mean_squared_error: 134.3445
Epoch 18/18
5667/5667 [==============================] - 14s 2ms/step - loss: 18030.0645 - root_mean_squared_error: 134.2761

The learned weight for your model is 0.0201
The learned bias for your model is 210.4003

## Use the model to make predictions
NOT TO DO:
Make predictions using the same data for training.

In [16]:
def predict_house_values(n, feature, label):
  """Predict house values based on a feature."""

  batch = training_df[feature][10000:10000 + n]
  predicted_values = my_model.predict_on_batch(x=batch)

  print("feature   label          predicted")
  print("  value   value          value")
  print("          in thousand$   in thousand$")
  print("--------------------------------------")
  for i in range(n):
    print ("%5.0f %6.0f %15.0f" % (training_df[feature][10000 + i],
                                   training_df[label][10000 + i],
                                   predicted_values[i][0] ))

In [17]:
predict_house_values(10, my_feature, my_label)

feature   label          predicted
  value   value          value
          in thousand$   in thousand$
--------------------------------------
 1960     53             239
 3400     92             280
 3677     69             288
 2202     62             246
 2403     80             252
 5652    295             344
 3318    500             278
 2552    342             256
 1364    118             223
 3468    128             282

## Define a synthetic feature
As `total_rooms` and `population` were not useful features. Perhaps though, the *ratio* of `total_rooms` to `population` might have some predictive power. That is, perhaps block density relates to median house value.

To explore this hypothesis, do the following: 

1. Create a [synthetic feature](https://developers.google.com/machine-learning/glossary/#synthetic_feature) that's a ratio of `total_rooms` to `population`. (If you are new to pandas DataFrames, please study the [Pandas DataFrame Ultraquick Tutorial](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/pandas_dataframe_ultraquick_tutorial.ipynb?utm_source=linearregressionreal-colab&utm_medium=colab&utm_campaign=colab-external&utm_content=pandas_tf2-colab&hl=en).)
2. Tune the three hyperparameters.
3. Determine whether this synthetic feature produces 
   a lower loss value than any of the single features you 
   tried earlier in this exercise.

In [ ]:
training_df["rooms_per_person"] = training_df["total_rooms"] / training_df["population"]

my_feature = "rooms_per_person"

learning_rate = 0.1
epochs = 30
batch_size = 3

my_model = build_model(learning_rate)
wei